// Auto-generated seed data from lab calibration workbook (2026)
// كل الأجهزة هنا أجهزة مساندة؛ قسم الأجهزة الرئيسية يُملأ يدوياً
const SEED_DEPARTMENTS = [
  {
    "id": "chemical-contaminants",
    "slug": "chemical-contaminants",
    "nameEn": "Chemical Contaminants",
    "nameAr": "الملوثات الكيميائية",
    "icon": "🧪",
    "color": "#6366f1"
  },
  {
    "id": "antibiotics-hormones",
    "slug": "antibiotics-hormones",
    "nameEn": "Antibiotics & Hormones",
    "nameAr": "المضادات الحيوية والهرمونات",
    "icon": "💊",
    "color": "#0891b2"
  },
  {
    "id": "pesticide-residues",
    "slug": "pesticide-residues",
    "nameEn": "Pesticide Residues",
    "nameAr": "متبقيات المبيدات",
    "icon": "🌿",
    "color": "#16a34a"
  },
  {
    "id": "food-fraud",
    "slug": "food-fraud",
    "nameEn": "Food Fraud",
    "nameAr": "غش الأغذية",
    "icon": "🍽️",
    "color": "#dc2626"
  },
  {
    "id": "toxins",
    "slug": "toxins",
    "nameEn": "Toxins",
    "nameAr": "السموم",
    "icon": "☠️",
    "color": "#9333ea"
  }
];

const SEED_DEVICES = [
  {
    "id": "fcl-cc-763",
    "departmentId": "chemical-contaminants",
    "unit": "Inorganic",
    "category": "supporting",
    "oldCode": "FR-CH-763",
    "newCode": "FCL-CC-763",
    "name": "RMS Wireless Data Logger",
    "manufacturer": "Rotronic",
    "serial": "0024009723",
    "model": "RMS-MLOG-T10-868",
    "test": "Temperature",
    "certNumber": "QCCC-659-10-2025",
    "calCompany": "Quality Compliance",
    "calDate": "22/10/2025",
    "dueDate": "22/10/2026",
    "remarks": "",
    "condition": "operational",
    "certificateId": ""
  },
  {
    "id": "fcl-cc-035",
    "departmentId": "chemical-contaminants",
    "unit": "Inorganic",
    "category": "supporting",
    "oldCode": "RLFC-IC-035",
    "newCode": "FCL-CC-035",
    "name": "Hot Plate",
    "manufacturer": "VELP Scientifica",
    "serial": "345144",
    "model": "F20500011",
    "test": "Temperature",
    "certNumber": "QCCC-856-10-2025",
    "calCompany": "Quality Compliance",
    "calDate": "29/09/2025",
    "dueDate": "29/09/2027",
    "remarks": "",
    "condition": "operational",
    "certificateId": ""
  },
  {
    "id": "fcl-cc-742",
    "departmentId": "chemical-contaminants",
    "unit": "Inorganic",
    "category": "supporting",
    "oldCode": "FR-CH-742",
    "newCode": "FCL-CC-742",
    "name": "RMS Wireless Data Logger",
    "manufacturer": "Rotronic",
    "serial": "0024004290",
    "model": "RMS-MLOG-T10-868",
    "test": "Temperature",
    "certNumber": "QCCC-654-10-2025",
    "calCompany": "Quality Compliance",
    "calDate": "22/10/2025",
    "dueDate": "22/10/2026",
    "remarks": "",
    "condition": "operational",
    "certificateId": ""
  },
  {
    "id": "fcl-cc-737",
    "departmentId": "chemical-contaminants",
    "unit": "Inorganic",
    "category": "supporting",
    "oldCode": "FR-CH-737",
    "newCode": "FCL-CC-737",
    "name": "Temperature & Humidity Data Logger",
    "manufacturer": "Rotronic",
    "serial": "0024018352",
    "model": "RMS-LOG-868",
    "test": "Temperature / Humidity",
    "certNumber": "QCCC-814-10-2025 / QCCC-815-10-2025",
    "calCompany": "Quality Compliance",
    "calDate": "22/10/2025",
    "dueDate": "22/10/2026",
    "remarks": "Merged duplicated temperature and humidity certificates",
    "condition": "operational",
    "certificateId": ""
  },
  {
    "id": "fcl-cc-125",
    "departmentId": "chemical-contaminants",
    "unit": "Inorganic",
    "category": "supporting",
    "oldCode": "FR-CH-125",
    "newCode": "FCL-CC-125",
    "name": "Water Bath",
    "manufacturer": "JRS",
    "serial": "120130-10",
    "model": "JSWB-30T",
    "test": "Temperature",
    "certNumber": "QCCC-864-10-2025",
    "calCompany": "Quality Compliance",
    "calDate": "31/08/2025",
    "dueDate": "31/08/2027",
    "remarks": "",
    "condition": "operational",
    "certificateId": ""
  },
  {
    "id": "fcl-cc-739",
    "departmentId": "chemical-contaminants",
    "unit": "Inorganic",
    "category": "supporting",
    "oldCode": "FR-CH-739",
    "newCode": "FCL-CC-739",
    "name": "Temperature & Humidity Data Logger",
    "manufacturer": "Rotronic",
    "serial": "0024018396",
    "model": "RMS-LOG-868",
    "test": "Temperature",
    "certNumber": "QCCC-818-10-2025",
    "calCompany": "Quality Compliance",
    "calDate": "22/10/2025",
    "dueDate": "22/10/2026",
    "remarks": "",
    "condition": "operational",
    "certificateId": ""
  },
  {
    "id": "fcl-cc-738",
    "departmentId": "chemical-contaminants",
    "unit": "Inorganic",
    "category": "supporting",
    "oldCode": "FR-CH-738",
    "newCode": "FCL-CC-738",
    "name": "Temperature & Humidity Data Logger",
    "manufacturer": "Rotronic",
    "serial": "0024018303",
    "model": "RMS-LOG-868",
    "test": "Temperature / Humidity",
    "certNumber": "QCCC-816-10-2025 / QCCC-817-10-2025",
    "calCompany": "Quality Compliance",
    "calDate": "22/10/2025",
    "dueDate": "22/10/2026",
    "remarks": "Merged duplicated temperature and humidity certificates",
    "condition": "operational",
    "certificateId": ""
  },
  {
    "id": "fcl-cc-129",
    "departmentId": "chemical-contaminants",
    "unit": "Inorganic",
    "category": "supporting",
    "oldCode": "FR-CH-129",
    "newCode": "FCL-CC-129",
    "name": "Conductivity Meter",
    "manufacturer": "Thermo",
    "serial": "V10263",
    "model": "N/A",
    "test": "Conductivity",
    "certNumber": "QCCR-12242-10-2025",
    "calCompany": "Quality Compliance",
    "calDate": "01/09/2025",
    "dueDate": "01/09/2026",
    "remarks": "",
    "condition": "operational",
    "certificateId": ""
  },
  {
    "id": "fcl-cc-741",
    "departmentId": "chemical-contaminants",
    "unit": "Inorganic",
    "category": "supporting",
    "oldCode": "FR-CH-741",
    "newCode": "FCL-CC-741",
    "name": "RMS Wireless Data Logger",
    "manufacturer": "Rotronic",
    "serial": "0024009735",
    "model": "RMS-MLOG-T10-868",
    "test": "Temperature",
    "certNumber": "QCCC-653-10-2025",
    "calCompany": "Quality Compliance",
    "calDate": "22/10/2025",
    "dueDate": "22/10/2026",
    "remarks": "",
    "condition": "operational",
    "certificateId": ""
  },
  {
    "id": "fcl-cc-740",
    "departmentId": "chemical-contaminants",
    "unit": "Inorganic",
    "category": "supporting",
    "oldCode": "FR-CH-740",
    "newCode": "FCL-CC-740",
    "name": "RMS Wireless Data Logger",
    "manufacturer": "Rotronic",
    "serial": "0024009733",
    "model": "RMS-MLOG-T10-868",
    "test": "Temperature",
    "certNumber": "QCCC-652-10-2025",
    "calCompany": "Quality Compliance",
    "calDate": "22/10/2025",
    "dueDate": "22/10/2026",
    "remarks": "",
    "condition": "operational",
    "certificateId": ""
  },
  {
    "id": "fcl-cc-089",
    "departmentId": "chemical-contaminants",
    "unit": "Inorganic",
    "category": "supporting",
    "oldCode": "FR-CH-089",
    "newCode": "FCL-CC-089",
    "name": "Digital Balance",
    "manufacturer": "Mettler Toledo",
    "serial": "1120291702",
    "model": "B204-S",
    "test": "Mass / Balance",
    "certNumber": "C25WB0334",
    "calCompany": "Omega Calibration & Testing",
    "calDate": "01/09/2025",
    "dueDate": "01/09/2026",
    "remarks": "",
    "condition": "operational",
    "certificateId": ""
  },
  {
    "id": "fcl-cc-030",
    "departmentId": "chemical-contaminants",
    "unit": "Inorganic",
    "category": "supporting",
    "oldCode": "RLFC-IC-030",
    "newCode": "FCL-CC-030",
    "name": "Water Bath",
    "manufacturer": "Stuart",
    "serial": "R690000423",
    "model": "SWB6D",
    "test": "Temperature",
    "certNumber": "QCCC-874-10-2025",
    "calCompany": "Quality Compliance",
    "calDate": "02/09/2025",
    "dueDate": "02/09/2027",
    "remarks": "",
    "condition": "operational",
    "certificateId": ""
  },
  {
    "id": "fcl-cc-053",
    "departmentId": "chemical-contaminants",
    "unit": "Inorganic",
    "category": "supporting",
    "oldCode": "RLFC-IC-053",
    "newCode": "FCL-CC-053",
    "name": "Hot Plate",
    "manufacturer": "VELP Scientifica",
    "serial": "345144",
    "model": "F20500011",
    "test": "Temperature",
    "certNumber": "QCCC-856-10-2025",
    "calCompany": "Quality Compliance",
    "calDate": "29/09/2025",
    "dueDate": "29/09/2027",
    "remarks": "",
    "condition": "operational",
    "certificateId": ""
  },
  {
    "id": "fcl-cc-029",
    "departmentId": "chemical-contaminants",
    "unit": "Inorganic",
    "category": "supporting",
    "oldCode": "RLFC-IC-029",
    "newCode": "FCL-CC-029",
    "name": "Water Bath",
    "manufacturer": "Elma Sonic",
    "serial": "102229105",
    "model": "S60H",
    "test": "Temperature",
    "certNumber": "QCCC-866-10-2025",
    "calCompany": "Quality Compliance",
    "calDate": "02/09/2025",
    "dueDate": "02/09/2027",
    "remarks": "",
    "condition": "operational",
    "certificateId": ""
  },
  {
    "id": "fcl-cc-031",
    "departmentId": "chemical-contaminants",
    "unit": "Inorganic",
    "category": "supporting",
    "oldCode": "RLFC-IC-031",
    "newCode": "FCL-CC-031",
    "name": "Hot Plate",
    "manufacturer": "VELP Scientifica",
    "serial": "342021",
    "model": "F20500011",
    "test": "Temperature",
    "certNumber": "QCCC-855-10-2025",
    "calCompany": "Quality Compliance",
    "calDate": "02/09/2025",
    "dueDate": "02/09/2027",
    "remarks": "",
    "condition": "operational",
    "certificateId": ""
  },
  {
    "id": "fcl-cc-027",
    "departmentId": "chemical-contaminants",
    "unit": "Inorganic",
    "category": "supporting",
    "oldCode": "RLFC-IC-027",
    "newCode": "FCL-CC-027",
    "name": "Oven",
    "manufacturer": "Binder",
    "serial": "16-11631",
    "model": "N/A",
    "test": "Temperature",
    "certNumber": "QCCC-884-10-2025",
    "calCompany": "Quality Compliance",
    "calDate": "02/09/2025",
    "dueDate": "02/09/2027",
    "remarks": "",
    "condition": "operational",
    "certificateId": ""
  },
  {
    "id": "fcl-cc-005",
    "departmentId": "chemical-contaminants",
    "unit": "Inorganic",
    "category": "supporting",
    "oldCode": "RLFC-IC-005",
    "newCode": "FCL-CC-005",
    "name": "pH Meter",
    "manufacturer": "HANNA",
    "serial": "02130001991",
    "model": "HI 5522",
    "test": "pH / Temperature",
    "certNumber": "083256 / QCCR-14898-12-2025",
    "calCompany": "Integrated Calibration Services; Quality Compliance",
    "calDate": "22/10/2025",
    "dueDate": "22/10/2026",
    "remarks": "Merged pH and temperature calibration records",
    "condition": "operational",
    "certificateId": ""
  },
  {
    "id": "fcl-cc-026",
    "departmentId": "chemical-contaminants",
    "unit": "Inorganic",
    "category": "supporting",
    "oldCode": "RLFC-IC-026",
    "newCode": "FCL-CC-026",
    "name": "Oven",
    "manufacturer": "Binder",
    "serial": "16-11632",
    "model": "N/A",
    "test": "Temperature",
    "certNumber": "QCCC-883-10-2025",
    "calCompany": "Quality Compliance",
    "calDate": "02/09/2025",
    "dueDate": "02/09/2027",
    "remarks": "",
    "condition": "operational",
    "certificateId": ""
  },
  {
    "id": "fcl-cc-054",
    "departmentId": "chemical-contaminants",
    "unit": "Inorganic",
    "category": "supporting",
    "oldCode": "RLFC-IC-054",
    "newCode": "FCL-CC-054",
    "name": "Centrifuge",
    "manufacturer": "Hermle",
    "serial": "60100480",
    "model": "Z206A",
    "test": "Speed",
    "certNumber": "QCCR-14298-12-2025",
    "calCompany": "Quality Compliance",
    "calDate": "02/12/2025",
    "dueDate": "02/12/2027",
    "remarks": "",
    "condition": "operational",
    "certificateId": ""
  },
  {
    "id": "fcl-cc-032",
    "departmentId": "chemical-contaminants",
    "unit": "Inorganic",
    "category": "supporting",
    "oldCode": "RLFC-GEN-032",
    "newCode": "FCL-CC-032",
    "name": "Temperature & Humidity Data Logger",
    "manufacturer": "Rotronic",
    "serial": "0024011988",
    "model": "RMS-LOG-868",
    "test": "Temperature / Humidity",
    "certNumber": "QCCC-840-10-2025 / QCCC-841-10-2025",
    "calCompany": "Quality Compliance",
    "calDate": "22/10/2025",
    "dueDate": "22/10/2026",
    "remarks": "Merged duplicated temperature and humidity certificates",
    "condition": "operational",
    "certificateId": ""
  },
  {
    "id": "fcl-cc-034",
    "departmentId": "chemical-contaminants",
    "unit": "Inorganic",
    "category": "supporting",
    "oldCode": "RLFC-GEN-034",
    "newCode": "FCL-CC-034",
    "name": "RMS Wireless Data Logger",
    "manufacturer": "Rotronic",
    "serial": "0024004332",
    "model": "RMS-MLOG-T10-868",
    "test": "Temperature",
    "certNumber": "QCCC-684-10-2025",
    "calCompany": "Quality Compliance",
    "calDate": "22/10/2025",
    "dueDate": "22/10/2026",
    "remarks": "",
    "condition": "operational",
    "certificateId": ""
  },
  {
    "id": "fcl-cc-033",
    "departmentId": "chemical-contaminants",
    "unit": "Inorganic",
    "category": "supporting",
    "oldCode": "RLFC-GEN-033",
    "newCode": "FCL-CC-033",
    "name": "RMS Wireless Data Logger",
    "manufacturer": "Rotronic",
    "serial": "0024004335",
    "model": "RMS-MLOG-T10-868",
    "test": "Temperature",
    "certNumber": "QCCC-683-10-2025",
    "calCompany": "Quality Compliance",
    "calDate": "22/10/2025",
    "dueDate": "22/10/2026",
    "remarks": "",
    "condition": "operational",
    "certificateId": ""
  },
  {
    "id": "fcl-cc-036",
    "departmentId": "chemical-contaminants",
    "unit": "Inorganic",
    "category": "supporting",
    "oldCode": "RLFC-GEN-036",
    "newCode": "FCL-CC-036",
    "name": "Temperature & Humidity Data Logger",
    "manufacturer": "Rotronic",
    "serial": "0024018387",
    "model": "RMS-LOG-868",
    "test": "Temperature / Humidity",
    "certNumber": "QCCC-842-10-2025 / QCCC-843-10-2025",
    "calCompany": "Quality Compliance",
    "calDate": "22/10/2025",
    "dueDate": "22/10/2026",
    "remarks": "Merged duplicated temperature and humidity certificates",
    "condition": "operational",
    "certificateId": ""
  },
  {
    "id": "fcl-cc-049",
    "departmentId": "chemical-contaminants",
    "unit": "Inorganic",
    "category": "supporting",
    "oldCode": "RLFC-IC-049",
    "newCode": "FCL-CC-049",
    "name": "Balance",
    "manufacturer": "Sartorius",
    "serial": "22006409",
    "model": "TE2145",
    "test": "Mass / Balance",
    "certNumber": "C25WB0343",
    "calCompany": "Omega Calibration & Testing",
    "calDate": "02/09/2025",
    "dueDate": "02/09/2026",
    "remarks": "",
    "condition": "operational",
    "certificateId": ""
  },
  {
    "id": "fcl-ha-013",
    "departmentId": "antibiotics-hormones",
    "unit": "",
    "category": "supporting",
    "oldCode": "RLFC-GEN-013",
    "newCode": "FCL-HA-013",
    "name": "RMS Wireless Data Logger",
    "manufacturer": "Rotronic",
    "serial": "0024004313",
    "model": "",
    "test": "Temperature",
    "certNumber": "QCCC-675-10-2025",
    "calCompany": "Quality Compliance",
    "calDate": "22/10/2025",
    "dueDate": "22/10/2026",
    "remarks": "",
    "condition": "operational",
    "certificateId": ""
  },
  {
    "id": "fcl-ha-761",
    "departmentId": "antibiotics-hormones",
    "unit": "",
    "category": "supporting",
    "oldCode": "FR-CH-761",
    "newCode": "FCL-HA-761",
    "name": "Temperature & Humidity Data Logger",
    "manufacturer": "Rotronic",
    "serial": "0024018385",
    "model": "",
    "test": "Humidity",
    "certNumber": "QCCC-825-10-2025",
    "calCompany": "Quality Compliance",
    "calDate": "22/10/2025",
    "dueDate": "22/10/2026",
    "remarks": "",
    "condition": "operational",
    "certificateId": ""
  },
  {
    "id": "fcl-ha-760",
    "departmentId": "antibiotics-hormones",
    "unit": "",
    "category": "supporting",
    "oldCode": "FR-CH-760",
    "newCode": "FCL-HA-760",
    "name": "Temperature & Humidity Data Logger",
    "manufacturer": "Rotronic",
    "serial": "0024018397",
    "model": "",
    "test": "Humidity",
    "certNumber": "QCCC-823-10-2025",
    "calCompany": "Quality Compliance",
    "calDate": "22/10/2025",
    "dueDate": "22/10/2026",
    "remarks": "",
    "condition": "operational",
    "certificateId": ""
  },
  {
    "id": "fcl-ha-337",
    "departmentId": "antibiotics-hormones",
    "unit": "",
    "category": "supporting",
    "oldCode": "FR-CH-337",
    "newCode": "FCL-HA-337",
    "name": "Centrifuge",
    "manufacturer": "Hettich",
    "serial": "67100002",
    "model": "",
    "test": "Speed",
    "certNumber": "QCCR-12483-09-2025",
    "calCompany": "Quality Compliance",
    "calDate": "02/09/2025",
    "dueDate": "02/09/2027",
    "remarks": "",
    "condition": "operational",
    "certificateId": ""
  },
  {
    "id": "fcl-ha-762",
    "departmentId": "antibiotics-hormones",
    "unit": "",
    "category": "supporting",
    "oldCode": "FR-CH-762",
    "newCode": "FCL-HA-762",
    "name": "RMS Wireless Data Logger",
    "manufacturer": "Rotronic",
    "serial": "0024004602",
    "model": "",
    "test": "Temperature",
    "certNumber": "QCCC-658-10-2025",
    "calCompany": "Quality Compliance",
    "calDate": "22/10/2025",
    "dueDate": "22/10/2026",
    "remarks": "",
    "condition": "operational",
    "certificateId": ""
  },
  {
    "id": "fcl-ha-332",
    "departmentId": "antibiotics-hormones",
    "unit": "",
    "category": "supporting",
    "oldCode": "FR-CH-332",
    "newCode": "FCL-HA-332",
    "name": "Freezer",
    "manufacturer": "Evermed",
    "serial": "78278",
    "model": "",
    "test": "Temperature",
    "certNumber": "QCCC-915-10-2025",
    "calCompany": "Quality Compliance",
    "calDate": "31/08/2025",
    "dueDate": "31/08/2027",
    "remarks": "",
    "condition": "operational",
    "certificateId": ""
  },
  {
    "id": "fcl-ha-350",
    "departmentId": "antibiotics-hormones",
    "unit": "",
    "category": "supporting",
    "oldCode": "FR-CH-350",
    "newCode": "FCL-HA-350",
    "name": "Digital Balance",
    "manufacturer": "Sartorius",
    "serial": "27109414",
    "model": "",
    "test": "Mass / Balance",
    "certNumber": "QCCR-12469-10-2025",
    "calCompany": "Quality Compliance",
    "calDate": "01/09/2025",
    "dueDate": "01/09/2026",
    "remarks": "",
    "condition": "operational",
    "certificateId": ""
  },
  {
    "id": "fcl-ha-316",
    "departmentId": "antibiotics-hormones",
    "unit": "",
    "category": "supporting",
    "oldCode": "FR-CH-316",
    "newCode": "FCL-HA-316",
    "name": "Digital Balance",
    "manufacturer": "CHYO",
    "serial": "972552",
    "model": "",
    "test": "Mass / Balance",
    "certNumber": "QCCR-12468-10-2025",
    "calCompany": "Quality Compliance",
    "calDate": "01/09/2025",
    "dueDate": "01/09/2026",
    "remarks": "",
    "condition": "operational",
    "certificateId": ""
  },
  {
    "id": "fcl-ha-336",
    "departmentId": "antibiotics-hormones",
    "unit": "",
    "category": "supporting",
    "oldCode": "FR-CH-336",
    "newCode": "FCL-HA-336",
    "name": "Water Bath",
    "manufacturer": "Grant",
    "serial": "03046310",
    "model": "",
    "test": "Temperature",
    "certNumber": "QCCC-869-10-2025",
    "calCompany": "Quality Compliance",
    "calDate": "31/08/2025",
    "dueDate": "31/08/2027",
    "remarks": "",
    "condition": "operational",
    "certificateId": ""
  },
  {
    "id": "fcl-ha-325",
    "departmentId": "antibiotics-hormones",
    "unit": "",
    "category": "supporting",
    "oldCode": "FR-CH-325",
    "newCode": "FCL-HA-325",
    "name": "Water Bath",
    "manufacturer": "SCITEK",
    "serial": "1301",
    "model": "",
    "test": "Temperature",
    "certNumber": "QCCC-875-10-2025",
    "calCompany": "Quality Compliance",
    "calDate": "31/08/2025",
    "dueDate": "31/08/2027",
    "remarks": "",
    "condition": "operational",
    "certificateId": ""
  },
  {
    "id": "fcl-ha-004",
    "departmentId": "antibiotics-hormones",
    "unit": "",
    "category": "supporting",
    "oldCode": "RLFC-HA-004",
    "newCode": "FCL-HA-004",
    "name": "Digital Balance",
    "manufacturer": "Sartorius",
    "serial": "0034208452",
    "model": "",
    "test": "Mass / Balance",
    "certNumber": "QCCR-14879-12-2025",
    "calCompany": "Quality Compliance",
    "calDate": "23/12/2025",
    "dueDate": "23/12/2026",
    "remarks": "",
    "condition": "operational",
    "certificateId": ""
  },
  {
    "id": "fcl-ha-011",
    "departmentId": "antibiotics-hormones",
    "unit": "",
    "category": "supporting",
    "oldCode": "RLFC-HA-011",
    "newCode": "FCL-HA-011",
    "name": "Water Bath",
    "manufacturer": "Elma",
    "serial": "102225105",
    "model": "",
    "test": "Temperature",
    "certNumber": "QCCC-1043-12-2025",
    "calCompany": "Quality Compliance",
    "calDate": "23/12/2025",
    "dueDate": "23/12/2027",
    "remarks": "",
    "condition": "operational",
    "certificateId": ""
  },
  {
    "id": "fcl-ha-316-2",
    "departmentId": "antibiotics-hormones",
    "unit": "",
    "category": "supporting",
    "oldCode": "FR-CH-316",
    "newCode": "FCL-HA-316",
    "name": "Digital Balance",
    "manufacturer": "CHYO",
    "serial": "972552",
    "model": "",
    "test": "Mass / Balance",
    "certNumber": "C25WB0325",
    "calCompany": "Omega Calibration & Testing",
    "calDate": "01/09/2025",
    "dueDate": "01/09/2026",
    "remarks": "",
    "condition": "operational",
    "certificateId": ""
  },
  {
    "id": "fcl-ha-016",
    "departmentId": "antibiotics-hormones",
    "unit": "",
    "category": "supporting",
    "oldCode": "RLFC-HA-016",
    "newCode": "FCL-HA-016",
    "name": "Turbo Vap LV Concentration Evaporator",
    "manufacturer": "Caliper Live Science",
    "serial": "TV0913N15169",
    "model": "",
    "test": "Temperature",
    "certNumber": "QCCC-1042-12-2025",
    "calCompany": "Quality Compliance",
    "calDate": "23/12/2025",
    "dueDate": "23/12/2027",
    "remarks": "",
    "condition": "operational",
    "certificateId": ""
  },
  {
    "id": "fcl-ha-763",
    "departmentId": "antibiotics-hormones",
    "unit": "",
    "category": "supporting",
    "oldCode": "FR-CH-763",
    "newCode": "FCL-HA-763",
    "name": "RMS Wireless Data Logger",
    "manufacturer": "Rotronic",
    "serial": "0024009723",
    "model": "",
    "test": "Temperature",
    "certNumber": "QCCC-659-10-2025",
    "calCompany": "Quality Compliance",
    "calDate": "22/10/2025",
    "dueDate": "22/10/2026",
    "remarks": "",
    "condition": "operational",
    "certificateId": ""
  },
  {
    "id": "fcl-ha-760-2",
    "departmentId": "antibiotics-hormones",
    "unit": "",
    "category": "supporting",
    "oldCode": "FR-CH-760",
    "newCode": "FCL-HA-760",
    "name": "Temperature & Humidity Data Logger",
    "manufacturer": "Rotronic",
    "serial": "0024018397",
    "model": "",
    "test": "Temperature",
    "certNumber": "QCCC-822-10-2025",
    "calCompany": "Quality Compliance",
    "calDate": "22/10/2025",
    "dueDate": "22/10/2026",
    "remarks": "",
    "condition": "operational",
    "certificateId": ""
  },
  {
    "id": "fcl-ha-761-2",
    "departmentId": "antibiotics-hormones",
    "unit": "",
    "category": "supporting",
    "oldCode": "FR-CH-761",
    "newCode": "FCL-HA-761",
    "name": "Temperature & Humidity Data Logger",
    "manufacturer": "Rotronic",
    "serial": "0024018385",
    "model": "",
    "test": "Temperature",
    "certNumber": "QCCC-824-10-2025",
    "calCompany": "Quality Compliance",
    "calDate": "22/10/2025",
    "dueDate": "22/10/2026",
    "remarks": "",
    "condition": "operational",
    "certificateId": ""
  },
  {
    "id": "fcl-ha-010",
    "departmentId": "antibiotics-hormones",
    "unit": "",
    "category": "supporting",
    "oldCode": "RLFC-HA-010",
    "newCode": "FCL-HA-010",
    "name": "Centrifuge",
    "manufacturer": "Hermle",
    "serial": "67160029",
    "model": "",
    "test": "Speed",
    "certNumber": "QCCR-12482-09-2025",
    "calCompany": "Quality Compliance",
    "calDate": "02/09/2025",
    "dueDate": "02/09/2027",
    "remarks": "",
    "condition": "operational",
    "certificateId": ""
  },
  {
    "id": "fcl-ha-003",
    "departmentId": "antibiotics-hormones",
    "unit": "",
    "category": "supporting",
    "oldCode": "RLFC-HA-003",
    "newCode": "FCL-HA-003",
    "name": "Centrifuge",
    "manufacturer": "Eppendorf",
    "serial": "5804EP064513",
    "model": "",
    "test": "Speed",
    "certNumber": "QCCR-12481-09-2025",
    "calCompany": "Quality Compliance",
    "calDate": "02/09/2025",
    "dueDate": "02/09/2027",
    "remarks": "",
    "condition": "operational",
    "certificateId": ""
  },
  {
    "id": "fcl-ha-014",
    "departmentId": "antibiotics-hormones",
    "unit": "",
    "category": "supporting",
    "oldCode": "RLFC-HA-014",
    "newCode": "FCL-HA-014",
    "name": "Freezer",
    "manufacturer": "SAMSUNG",
    "serial": "06G543CGB00118F",
    "model": "",
    "test": "Temperature",
    "certNumber": "QCCC-914-10-2025",
    "calCompany": "Quality Compliance",
    "calDate": "02/09/2025",
    "dueDate": "02/09/2027",
    "remarks": "",
    "condition": "operational",
    "certificateId": ""
  },
  {
    "id": "fcl-ha-350-2",
    "departmentId": "antibiotics-hormones",
    "unit": "",
    "category": "supporting",
    "oldCode": "FR-CH-350",
    "newCode": "FCL-HA-350",
    "name": "Digital Balance",
    "manufacturer": "Sartorius",
    "serial": "27109414",
    "model": "",
    "test": "Mass / Balance",
    "certNumber": "C25WB0326",
    "calCompany": "Omega Calibration & Testing",
    "calDate": "01/09/2025",
    "dueDate": "01/09/2026",
    "remarks": "",
    "condition": "operational",
    "certificateId": ""
  },
  {
    "id": "fcl-ff-619",
    "departmentId": "food-fraud",
    "unit": "General Analysis Unit",
    "category": "supporting",
    "oldCode": "FR-CH-619",
    "newCode": "FCL-FF-619",
    "name": "Refrigerator",
    "manufacturer": "",
    "serial": "80778",
    "model": "",
    "test": "Temperature",
    "certNumber": "QCCC-908-10-2025",
    "calCompany": "Quality Compliance",
    "calDate": "29/09/2025",
    "dueDate": "29/09/2027",
    "remarks": "",
    "condition": "operational",
    "certificateId": ""
  },
  {
    "id": "fcl-ff-054",
    "departmentId": "food-fraud",
    "unit": "General Analysis Unit",
    "category": "supporting",
    "oldCode": "FR-CH-054",
    "newCode": "FCL-FF-054",
    "name": "Refrigerator",
    "manufacturer": "",
    "serial": "147610",
    "model": "",
    "test": "Temperature",
    "certNumber": "QCCC-909-10-2025",
    "calCompany": "Quality Compliance",
    "calDate": "29/09/2025",
    "dueDate": "29/09/2027",
    "remarks": "",
    "condition": "operational",
    "certificateId": ""
  },
  {
    "id": "fcl-ff-065",
    "departmentId": "food-fraud",
    "unit": "General Analysis Unit",
    "category": "supporting",
    "oldCode": "FR-CH-065",
    "newCode": "FCL-FF-065",
    "name": "Digital Balance",
    "manufacturer": "",
    "serial": "25003966",
    "model": "",
    "test": "Mass / Balance",
    "certNumber": "QCCR-12491-10-2025",
    "calCompany": "Quality Compliance",
    "calDate": "01/09/2025",
    "dueDate": "01/09/2026",
    "remarks": "",
    "condition": "operational",
    "certificateId": ""
  },
  {
    "id": "fcl-ff-537",
    "departmentId": "food-fraud",
    "unit": "General Analysis Unit",
    "category": "supporting",
    "oldCode": "FR-CH-537",
    "newCode": "FCL-FF-537",
    "name": "Digital Balance",
    "manufacturer": "",
    "serial": "N/A",
    "model": "",
    "test": "Mass / Balance",
    "certNumber": "QCCR-12497-10-2025",
    "calCompany": "Quality Compliance",
    "calDate": "01/09/2025",
    "dueDate": "01/09/2026",
    "remarks": "",
    "condition": "operational",
    "certificateId": ""
  },
  {
    "id": "fcl-ff-621",
    "departmentId": "food-fraud",
    "unit": "General Analysis Unit",
    "category": "supporting",
    "oldCode": "FR-CH-621",
    "newCode": "FCL-FF-621",
    "name": "Hot Plate",
    "manufacturer": "",
    "serial": "R390000361",
    "model": "",
    "test": "Temperature",
    "certNumber": "QCCC-846-10-2025",
    "calCompany": "Quality Compliance",
    "calDate": "01/09/2025",
    "dueDate": "01/09/2027",
    "remarks": "",
    "condition": "operational",
    "certificateId": ""
  },
  {
    "id": "fcl-ff-622",
    "departmentId": "food-fraud",
    "unit": "General Analysis Unit",
    "category": "supporting",
    "oldCode": "FR-CH-622",
    "newCode": "FCL-FF-622",
    "name": "Hot Plate",
    "manufacturer": "",
    "serial": "R390000364",
    "model": "",
    "test": "Temperature",
    "certNumber": "QCCC-847-10-2025",
    "calCompany": "Quality Compliance",
    "calDate": "01/09/2025",
    "dueDate": "01/09/2027",
    "remarks": "",
    "condition": "operational",
    "certificateId": ""
  },
  {
    "id": "fcl-ff-022",
    "departmentId": "food-fraud",
    "unit": "General Analysis Unit",
    "category": "supporting",
    "oldCode": "FR-CH-022",
    "newCode": "FCL-FF-022",
    "name": "Hot Plate",
    "manufacturer": "",
    "serial": "345121",
    "model": "",
    "test": "Temperature",
    "certNumber": "QCCC-853-10-2025",
    "calCompany": "Quality Compliance",
    "calDate": "29/09/2025",
    "dueDate": "29/09/2027",
    "remarks": "",
    "condition": "operational",
    "certificateId": ""
  },
  {
    "id": "fcl-ff-538",
    "departmentId": "food-fraud",
    "unit": "General Analysis Unit",
    "category": "supporting",
    "oldCode": "FR-CH-538",
    "newCode": "FCL-FF-538",
    "name": "Water Bath",
    "manufacturer": "",
    "serial": "UE1532012",
    "model": "",
    "test": "Temperature",
    "certNumber": "QCCC-863-10-2025",
    "calCompany": "Quality Compliance",
    "calDate": "31/08/2025",
    "dueDate": "31/08/2027",
    "remarks": "",
    "condition": "operational",
    "certificateId": ""
  },
  {
    "id": "fcl-ff-524",
    "departmentId": "food-fraud",
    "unit": "General Analysis Unit",
    "category": "supporting",
    "oldCode": "FR-CH-524",
    "newCode": "FCL-FF-524",
    "name": "Water Bath",
    "manufacturer": "",
    "serial": "UE1532012",
    "model": "",
    "test": "Temperature",
    "certNumber": "QCCC-862-10-2025",
    "calCompany": "Quality Compliance",
    "calDate": "31/08/2025",
    "dueDate": "31/08/2027",
    "remarks": "",
    "condition": "operational",
    "certificateId": ""
  },
  {
    "id": "fcl-ff-530",
    "departmentId": "food-fraud",
    "unit": "General Analysis Unit",
    "category": "supporting",
    "oldCode": "FR-CH-530",
    "newCode": "FCL-FF-530",
    "name": "Oven",
    "manufacturer": "",
    "serial": "321143",
    "model": "",
    "test": "Temperature",
    "certNumber": "QCCC-880-10-2025",
    "calCompany": "Quality Compliance",
    "calDate": "31/08/2025",
    "dueDate": "31/08/2027",
    "remarks": "",
    "condition": "operational",
    "certificateId": ""
  },
  {
    "id": "fcl-ff-058",
    "departmentId": "food-fraud",
    "unit": "General Analysis Unit",
    "category": "supporting",
    "oldCode": "FR-CH-058",
    "newCode": "FCL-FF-058",
    "name": "Oven",
    "manufacturer": "",
    "serial": "100112-01",
    "model": "",
    "test": "Temperature",
    "certNumber": "QCCC-881-10-2025",
    "calCompany": "Quality Compliance",
    "calDate": "31/08/2025",
    "dueDate": "31/08/2027",
    "remarks": "",
    "condition": "operational",
    "certificateId": ""
  },
  {
    "id": "fcl-ff-528",
    "departmentId": "food-fraud",
    "unit": "General Analysis Unit",
    "category": "supporting",
    "oldCode": "FR-CH-528",
    "newCode": "FCL-FF-528",
    "name": "Oven",
    "manufacturer": "",
    "serial": "16-11630",
    "model": "",
    "test": "Temperature",
    "certNumber": "QCCC-885-10-2025",
    "calCompany": "Quality Compliance",
    "calDate": "31/08/2025",
    "dueDate": "31/08/2027",
    "remarks": "",
    "condition": "operational",
    "certificateId": ""
  },
  {
    "id": "fcl-ff-072",
    "departmentId": "food-fraud",
    "unit": "General Analysis Unit",
    "category": "supporting",
    "oldCode": "FR-CH-072",
    "newCode": "FCL-FF-072",
    "name": "Water Bath",
    "manufacturer": "",
    "serial": "10149355",
    "model": "",
    "test": "Temperature",
    "certNumber": "QCCC-878-10-2025",
    "calCompany": "Quality Compliance",
    "calDate": "31/08/2025",
    "dueDate": "31/08/2027",
    "remarks": "",
    "condition": "operational",
    "certificateId": ""
  },
  {
    "id": "fcl-ff-071",
    "departmentId": "food-fraud",
    "unit": "General Analysis Unit",
    "category": "supporting",
    "oldCode": "FR-CH-071",
    "newCode": "FCL-FF-071",
    "name": "Water Bath",
    "manufacturer": "",
    "serial": "U33671209",
    "model": "",
    "test": "Temperature",
    "certNumber": "QCCC-860-10-2025",
    "calCompany": "Quality Compliance",
    "calDate": "31/08/2025",
    "dueDate": "31/08/2027",
    "remarks": "",
    "condition": "operational",
    "certificateId": ""
  },
  {
    "id": "fcl-ff-525",
    "departmentId": "food-fraud",
    "unit": "General Analysis Unit",
    "category": "supporting",
    "oldCode": "FR-CH-525",
    "newCode": "FCL-FF-525",
    "name": "Water Bath",
    "manufacturer": "",
    "serial": "U33701209",
    "model": "",
    "test": "Temperature",
    "certNumber": "QCCC-861-10-2025",
    "calCompany": "Quality Compliance",
    "calDate": "31/08/2025",
    "dueDate": "31/08/2027",
    "remarks": "",
    "condition": "operational",
    "certificateId": ""
  },
  {
    "id": "fcl-ff-543",
    "departmentId": "food-fraud",
    "unit": "General Analysis Unit",
    "category": "supporting",
    "oldCode": "FR-CH-543",
    "newCode": "FCL-FF-543",
    "name": "pH Meter",
    "manufacturer": "",
    "serial": "X53248",
    "model": "",
    "test": "pH",
    "certNumber": "083262",
    "calCompany": "Integrated Calibration Services",
    "calDate": "22/10/2025",
    "dueDate": "22/10/2026",
    "remarks": "",
    "condition": "operational",
    "certificateId": ""
  },
  {
    "id": "fcl-ff-526",
    "departmentId": "food-fraud",
    "unit": "General Analysis Unit",
    "category": "supporting",
    "oldCode": "FR-CH-526",
    "newCode": "FCL-FF-526",
    "name": "Centrifuge",
    "manufacturer": "",
    "serial": "5424CQ955801",
    "model": "",
    "test": "Speed",
    "certNumber": "QCCR-12232-10-2025",
    "calCompany": "Quality Compliance",
    "calDate": "31/08/2025",
    "dueDate": "31/08/2027",
    "remarks": "",
    "condition": "operational",
    "certificateId": ""
  },
  {
    "id": "fcl-ff-543-2",
    "departmentId": "food-fraud",
    "unit": "General Analysis Unit",
    "category": "supporting",
    "oldCode": "FR-CH-543",
    "newCode": "FCL-FF-543",
    "name": "pH Meter",
    "manufacturer": "",
    "serial": "X53248",
    "model": "",
    "test": "pH / Temperature",
    "certNumber": "QCCR-14900-12-2025",
    "calCompany": "Quality Compliance",
    "calDate": "22/10/2025",
    "dueDate": "22/10/2026",
    "remarks": "",
    "condition": "operational",
    "certificateId": ""
  },
  {
    "id": "fcl-ff-539",
    "departmentId": "food-fraud",
    "unit": "General Analysis Unit",
    "category": "supporting",
    "oldCode": "FR-CH-539",
    "newCode": "FCL-FF-539",
    "name": "Thermo Mixer",
    "manufacturer": "",
    "serial": "5387DJ900173",
    "model": "",
    "test": "Temperature",
    "certNumber": "QCCC-1038-12-2025",
    "calCompany": "Quality Compliance",
    "calDate": "23/12/2025",
    "dueDate": "23/12/2027",
    "remarks": "",
    "condition": "operational",
    "certificateId": ""
  },
  {
    "id": "fcl-ff-537-2",
    "departmentId": "food-fraud",
    "unit": "General Analysis Unit",
    "category": "supporting",
    "oldCode": "FR-CH-537",
    "newCode": "FCL-FF-537",
    "name": "Digital Balance",
    "manufacturer": "",
    "serial": "524286",
    "model": "",
    "test": "Mass / Balance",
    "certNumber": "C25WB0339",
    "calCompany": "Omega Calibration & Testing",
    "calDate": "01/09/2025",
    "dueDate": "01/09/2026",
    "remarks": "",
    "condition": "operational",
    "certificateId": ""
  },
  {
    "id": "fcl-ff-065-2",
    "departmentId": "food-fraud",
    "unit": "General Analysis Unit",
    "category": "supporting",
    "oldCode": "FR-CH-065",
    "newCode": "FCL-FF-065",
    "name": "Digital Balance",
    "manufacturer": "",
    "serial": "25003966",
    "model": "",
    "test": "Mass / Balance",
    "certNumber": "C25WB0333",
    "calCompany": "Omega Calibration & Testing",
    "calDate": "01/09/2025",
    "dueDate": "01/09/2026",
    "remarks": "",
    "condition": "operational",
    "certificateId": ""
  },
  {
    "id": "fcl-ff-384",
    "departmentId": "food-fraud",
    "unit": "Food Additives Unit",
    "category": "supporting",
    "oldCode": "FR-CH-384",
    "newCode": "FCL-FF-384",
    "name": "Digital Balance",
    "manufacturer": "",
    "serial": "34208453",
    "model": "",
    "test": "Mass / Balance",
    "certNumber": "C25WB0337 / QCCR-12495-10-2025",
    "calCompany": "Omega Calibration & Testing / Quality Compliance",
    "calDate": "01/09/2025",
    "dueDate": "01/09/2026",
    "remarks": "",
    "condition": "operational",
    "certificateId": ""
  },
  {
    "id": "fcl-ff-502",
    "departmentId": "food-fraud",
    "unit": "Food Additives Unit",
    "category": "supporting",
    "oldCode": "FR-CH-502",
    "newCode": "FCL-FF-502",
    "name": "Water Bath",
    "manufacturer": "",
    "serial": "102242105",
    "model": "",
    "test": "Temperature",
    "certNumber": "QCCC-1002-12-2025",
    "calCompany": "Quality Compliance",
    "calDate": "01/12/2025",
    "dueDate": "01/12/2027",
    "remarks": "",
    "condition": "operational",
    "certificateId": ""
  },
  {
    "id": "fcl-ff-385",
    "departmentId": "food-fraud",
    "unit": "Food Additives Unit",
    "category": "supporting",
    "oldCode": "FR-CH-385",
    "newCode": "FCL-FF-385",
    "name": "Centrifuge",
    "manufacturer": "",
    "serial": "000166-80-00",
    "model": "",
    "test": "Speed",
    "certNumber": "QCCR-12228-10-2025",
    "calCompany": "Quality Compliance",
    "calDate": "31/08/2025",
    "dueDate": "31/08/2027",
    "remarks": "",
    "condition": "operational",
    "certificateId": ""
  },
  {
    "id": "fcl-ff-770",
    "departmentId": "food-fraud",
    "unit": "Food Additives Unit",
    "category": "supporting",
    "oldCode": "FR-CH-770",
    "newCode": "FCL-FF-770",
    "name": "Temperature and Humidity Datalogger",
    "manufacturer": "",
    "serial": "0024011953",
    "model": "",
    "test": "Temperature / Humidity",
    "certNumber": "QCCC-826-10-2025 / QCCC-827-10-2025",
    "calCompany": "Quality Compliance",
    "calDate": "22/10/2025",
    "dueDate": "22/10/2026",
    "remarks": "",
    "condition": "operational",
    "certificateId": ""
  },
  {
    "id": "fcl-ff-774",
    "departmentId": "food-fraud",
    "unit": "Food Additives Unit",
    "category": "supporting",
    "oldCode": "FR-CH-774",
    "newCode": "FCL-FF-774",
    "name": "RMS Data Logger",
    "manufacturer": "",
    "serial": "0024004601",
    "model": "",
    "test": "Temperature",
    "certNumber": "QCCC-660-10-2025",
    "calCompany": "Quality Compliance",
    "calDate": "22/10/2025",
    "dueDate": "22/10/2026",
    "remarks": "",
    "condition": "operational",
    "certificateId": ""
  },
  {
    "id": "fcl-ff-370",
    "departmentId": "food-fraud",
    "unit": "Food Additives Unit",
    "category": "supporting",
    "oldCode": "FR-CH-370",
    "newCode": "FCL-FF-370",
    "name": "Hot Plate",
    "manufacturer": "",
    "serial": "23715775",
    "model": "",
    "test": "Temperature",
    "certNumber": "QCCC-845-10-2025",
    "calCompany": "Quality Compliance",
    "calDate": "01/09/2025",
    "dueDate": "01/09/2027",
    "remarks": "",
    "condition": "operational",
    "certificateId": ""
  }
];
